language: java

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

script:
  - ./gradlew build

notifications:
  email:
    recipients:
      - manuelf.mola@gmail.com
    on_success: change
    on_failure: always
